(function(){'use strict';
const frame=document.getElementById('app'),boot=document.getElementById('boot');
const VER='20260901-0440';
function route(){const p=new URLSearchParams(location.search);if(p.get('calc'))return '?calc='+encodeURIComponent(p.get('calc'));if(p.get('lab'))return '?lab='+encodeURIComponent(p.get('lab'));return ''}
function sync(){try{const w=frame.contentWindow,r=route();if(!w)return;if(r){w.history.replaceState(null,'',r);if(typeof w.ghRoute==='function')w.ghRoute()}else if(typeof w.ghRoute==='function')w.ghRoute()}catch(e){console.error(e)}}
function inject(w,name){return new Promise(ok=>{try{const old=w.document.querySelector('script[data-gh-inject="'+name+'"]');if(old)old.remove();const s=w.document.createElement('script');s.src=name+'?v='+VER;s.dataset.ghInject=name;s.onload=()=>ok();s.onerror=()=>ok();w.document.head.appendChild(s)}catch(e){ok()}})}
function repairRegistry(w){try{if(!Array.isArray(w.CALCS))return;const all=[],seen=new Set();function add(a){if(!Array.isArray(a))return;a.forEach(c=>{if(c&&typeof c.id==='string'&&!seen.has(c.id)){seen.add(c.id);all.push(c)}})}add(w.GH_MASTER_CALCS);add(w.GH_E1_CALCS);add(w.GH_E101_CALCS);add(w.DIESEL_CALCS);add(w.CALCS);try{Object.keys(w).forEach(k=>{if(/CALCS$/i.test(k))add(w[k])})}catch(e){}w.CALCS.splice(0,w.CALCS.length,...all);w.GH_MASTER_CALCS=all;w.__GH_FINAL_REGISTRY_COUNT=all.filter(c=>c.id!=='dashboard').length}catch(e){console.error('registry',e)}}
function installBack(w){if(w.__GH_APP_BACK)return;w.__GH_APP_BACK=true;w.addEventListener('popstate',sync);sync()}
function installCompactUnits(w){try{const d=w.document,old=d.querySelector('.gh-unit-toggle,.unit-toggle');if(!old||old.dataset.ghCompact)return;old.dataset.ghCompact='1';old.innerHTML='';old.className='gh-compact-units';const s=d.createElement('style');s.textContent='.gh-compact-units{position:relative}.gh-compact-units>button{border:1px solid rgba(215,161,31,.32);background:#0b0d10;color:#d7a11f;border-radius:8px;padding:7px 9px;font:800 10px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:.06em;cursor:pointer}.gh-compact-menu{position:absolute;right:0;top:calc(100% + 7px);min-width:150px;padding:6px;background:#111419;border:1px solid rgba(215,161,31,.3);border-radius:10px;box-shadow:0 12px 30px rgba(0,0,0,.45);z-index:500}.gh-compact-menu button{display:block;width:100%;padding:9px 10px;text-align:left;border:0;background:transparent;color:#c7cdd4;border-radius:7px;font:700 11px/1.2 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif}.gh-compact-menu button:hover{background:rgba(215,161,31,.1);color:#f2c65d}';d.head.appendChild(s);const b=d.createElement('button');b.type='button';b.textContent='UNITS';b.onclick=()=>{let m=old.querySelector('.gh-compact-menu');if(m){m.remove();return}m=d.createElement('div');m.className='gh-compact-menu';[['imperial','IMPERIAL'],['metric','METRIC']].forEach(([v,label])=>{const x=d.createElement('button');x.textContent=label;x.onclick=()=>{if(typeof w.setUnits==='function')w.setUnits(v);m.remove()};m.appendChild(x)});old.appendChild(m)};old.appendChild(b)}catch(e){console.error('units',e)}}
function installBackButton(w){try{const d=w.document;if(d.__GH_BACK_BUTTON)return;d.__GH_BACK_BUTTON=true;const s=d.createElement('style');s.textContent='.gh-app-back{display:inline-flex;align-items:center;gap:6px;margin-right:auto;border:1px solid rgba(215,161,31,.32);background:#0b0d10;color:#d7a11f;border-radius:9px;padding:7px 10px;font:800 11px/1 -apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;letter-spacing:.06em;cursor:pointer}.gh-app-back:hover{border-color:#d7a11f;background:rgba(215,161,31,.08)}';d.head.appendChild(s);const header=d.querySelector('.calc-header');if(header&&!header.querySelector('.gh-app-back')){const b=d.createElement('button');b.className='gh-app-back';b.type='button';b.textContent='← BACK';b.onclick=()=>{if(history.length>1)history.back();else{history.replaceState({},'',location.pathname);sync()}};header.insertBefore(b,header.firstChild)}}catch(e){console.error(e)}}
async function ready(){try{const w=frame.contentWindow;repairRegistry(w);await inject(w,'qa-math-corrections.js');await inject(w,'navigation-ux.js');installBack(w);installBackButton(w);installCompactUnits(w);sync();setTimeout(()=>{repairRegistry(w);installBackButton(w);installCompactUnits(w);sync()},300);setTimeout(()=>{repairRegistry(w);installBackButton(w);installCompactUnits(w);sync()},1000)}catch(e){console.error('Gearhead shell',e)}boot.classList.add('hide')}
frame.addEventListener('load',ready);window.addEventListener('popstate',sync);
})();